package org.test.webservice.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * TestWebServiceService service = new TestWebServiceService();
 * TestWebServiceDelegate portType = service.getTestWebServicePort();
 * portType.testWs(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "TestWebServiceService", targetNamespace = "http://ws.com/", wsdlLocation = "http://localhost:8080/MyBatis_Study/TestWebServicePort?wsdl")
public class TestWebServiceService extends Service {

	private final static URL TESTWEBSERVICESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(org.test.webservice.client.TestWebServiceService.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = org.test.webservice.client.TestWebServiceService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://localhost:8080/MyBatis_Study/TestWebServicePort?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/MyBatis_Study/TestWebServicePort?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		TESTWEBSERVICESERVICE_WSDL_LOCATION = url;
	}

	public TestWebServiceService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public TestWebServiceService() {
		super(TESTWEBSERVICESERVICE_WSDL_LOCATION, new QName("http://ws.com/",
				"TestWebServiceService"));
	}

	/**
	 * 
	 * @return returns TestWebServiceDelegate
	 */
	@WebEndpoint(name = "TestWebServicePort")
	public TestWebServiceDelegate getTestWebServicePort() {
		return super.getPort(new QName("http://ws.com/", "TestWebServicePort"),
				TestWebServiceDelegate.class);
	}

}
