package ctvit.hibernate.model;
// Generated 2016-10-13 15:36:54 by Hibernate Tools 4.0.0.Final

import java.util.Date;
import java.util.Set;

/**
 * RecordOrganization generated by hbm2java
 */
public class RecordOrganization implements java.io.Serializable {

	private String organizationid;
	private String organizationname;
	private Date organizationcreatetime;
	private Integer organizationflag;
	private String organizationdesc;
	private String organizationietitle;
	private String beizu;
	/*
	 *一个组织下有多个频道 一个频道属于一个组织  
	 *		      组织对频道是属于 一对多的关系
	 * 
	 */
	private Set<RecordChannel> channels;
	
	public Set<RecordChannel> getChannels() {
		return channels;
	}

	public void setChannels(Set<RecordChannel> channels) {
		this.channels = channels;
	}

	
	public RecordOrganization() {
	}

	public RecordOrganization(String organizationid) {
		this.organizationid = organizationid;
	}

	public RecordOrganization(String organizationid, String organizationname, Date organizationcreatetime,
			Integer organizationflag, String organizationdesc, String organizationietitle, String beizu) {
		this.organizationid = organizationid;
		this.organizationname = organizationname;
		this.organizationcreatetime = organizationcreatetime;
		this.organizationflag = organizationflag;
		this.organizationdesc = organizationdesc;
		this.organizationietitle = organizationietitle;
		this.beizu = beizu;
	}

	public String getOrganizationid() {
		return this.organizationid;
	}

	public void setOrganizationid(String organizationid) {
		this.organizationid = organizationid;
	}

	public String getOrganizationname() {
		return this.organizationname;
	}

	public void setOrganizationname(String organizationname) {
		this.organizationname = organizationname;
	}

	public Date getOrganizationcreatetime() {
		return this.organizationcreatetime;
	}

	public void setOrganizationcreatetime(Date organizationcreatetime) {
		this.organizationcreatetime = organizationcreatetime;
	}

	public Integer getOrganizationflag() {
		return this.organizationflag;
	}

	public void setOrganizationflag(Integer organizationflag) {
		this.organizationflag = organizationflag;
	}

	public String getOrganizationdesc() {
		return this.organizationdesc;
	}

	public void setOrganizationdesc(String organizationdesc) {
		this.organizationdesc = organizationdesc;
	}

	public String getOrganizationietitle() {
		return this.organizationietitle;
	}

	public void setOrganizationietitle(String organizationietitle) {
		this.organizationietitle = organizationietitle;
	}

	public String getBeizu() {
		return this.beizu;
	}

	public void setBeizu(String beizu) {
		this.beizu = beizu;
	}

}
