package ctvit.hibernate.model;
// Generated 2016-10-13 15:36:54 by Hibernate Tools 4.0.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * RecordUser generated by hbm2java
 */
public class RecordUser implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String userid;
	private String username;
	private String userpassword;
	private String organizationid;
	private Integer userflag;
	private Date createtime;
	private String creator;
	private Integer roleflag;
	private Set<RecordRole> roles;
	private Set<RecordUserRole> ru = new HashSet<RecordUserRole>();
	public Set<RecordUserRole> getRu() {
		return ru;
	}

	public void setRu(Set<RecordUserRole> ru) {
		this.ru = ru;
	}

	public Set<RecordRole> getRoles() {
		return roles;
	}

	public void setRoles(Set<RecordRole> roles) {
		this.roles = roles;
	}

	public RecordUser() {
	}

	public RecordUser(String userid) {
		this.userid = userid;
	}

	public RecordUser(String userid, String username, String userpassword, String organizationid, Integer userflag,
			Date createtime, String creator, Integer roleflag) {
		this.userid = userid;
		this.username = username;
		this.userpassword = userpassword;
		this.organizationid = organizationid;
		this.userflag = userflag;
		this.createtime = createtime;
		this.creator = creator;
		this.roleflag = roleflag;
	}

	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getUserpassword() {
		return this.userpassword;
	}

	public void setUserpassword(String userpassword) {
		this.userpassword = userpassword;
	}

	public String getOrganizationid() {
		return this.organizationid;
	}

	public void setOrganizationid(String organizationid) {
		this.organizationid = organizationid;
	}

	public Integer getUserflag() {
		return this.userflag;
	}

	public void setUserflag(Integer userflag) {
		this.userflag = userflag;
	}

	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	public Integer getRoleflag() {
		return this.roleflag;
	}

	public void setRoleflag(Integer roleflag) {
		this.roleflag = roleflag;
	}

}
