package ctvit.hibernate.model;
// Generated 2016-10-13 15:36:54 by Hibernate Tools 4.0.0.Final

/**
 * RecordUserRole generated by hbm2java
 */
public class RecordUserRole implements java.io.Serializable {

	private String relationid;
	private String userUserid;
	private String rolRoleid;

	public RecordUserRole() {
	}

	public RecordUserRole(String relationid) {
		this.relationid = relationid;
	}

	public RecordUserRole(String relationid, String userUserid, String rolRoleid) {
		this.relationid = relationid;
		this.userUserid = userUserid;
		this.rolRoleid = rolRoleid;
	}

	public String getRelationid() {
		return this.relationid;
	}

	public void setRelationid(String relationid) {
		this.relationid = relationid;
	}

	public String getUserUserid() {
		return this.userUserid;
	}

	public void setUserUserid(String userUserid) {
		this.userUserid = userUserid;
	}

	public String getRolRoleid() {
		return this.rolRoleid;
	}

	public void setRolRoleid(String rolRoleid) {
		this.rolRoleid = rolRoleid;
	}

}
