package ctvit.hibernate.model;
// Generated 2016-10-13 15:36:54 by Hibernate Tools 4.0.0.Final

/**
 * RecordUserRole generated by hbm2java
 */
public class RecordUserRole implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String relationid;
	private RecordUser user;
	private RecordRole role;

	
	public RecordUser getUser() {
		return user;
	}

	public void setUser(RecordUser user) {
		this.user = user;
	}

	public RecordRole getRole() {
		return role;
	}

	public void setRole(RecordRole role) {
		this.role = role;
	}

	
	public RecordUserRole() {
	}

	public RecordUserRole(String relationid) {
		this.relationid = relationid;
	}

	
	public String getRelationid() {
		return this.relationid;
	}

	public void setRelationid(String relationid) {
		this.relationid = relationid;
	}

}
