package ctvit.hibernate.model;
// Generated 2016-10-13 15:36:54 by Hibernate Tools 4.0.0.Final

import java.util.Date;

/**
 * RecordRole generated by hbm2java
 */
public class RecordRole implements java.io.Serializable {

	private String roleid;
	private String rolename;
	private String organizationid;
	private String roledesc;
	private Integer roleflag;
	private Date createtime;
	private byte[] rolerights;
	private Date updatecreatetime;
	private String updateuserid;

	public RecordRole() {
	}

	public RecordRole(String roleid) {
		this.roleid = roleid;
	}

	public RecordRole(String roleid, String rolename, String organizationid, String roledesc, Integer roleflag,
			Date createtime, byte[] rolerights, Date updatecreatetime, String updateuserid) {
		this.roleid = roleid;
		this.rolename = rolename;
		this.organizationid = organizationid;
		this.roledesc = roledesc;
		this.roleflag = roleflag;
		this.createtime = createtime;
		this.rolerights = rolerights;
		this.updatecreatetime = updatecreatetime;
		this.updateuserid = updateuserid;
	}

	public String getRoleid() {
		return this.roleid;
	}

	public void setRoleid(String roleid) {
		this.roleid = roleid;
	}

	public String getRolename() {
		return this.rolename;
	}

	public void setRolename(String rolename) {
		this.rolename = rolename;
	}

	public String getOrganizationid() {
		return this.organizationid;
	}

	public void setOrganizationid(String organizationid) {
		this.organizationid = organizationid;
	}

	public String getRoledesc() {
		return this.roledesc;
	}

	public void setRoledesc(String roledesc) {
		this.roledesc = roledesc;
	}

	public Integer getRoleflag() {
		return this.roleflag;
	}

	public void setRoleflag(Integer roleflag) {
		this.roleflag = roleflag;
	}

	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public byte[] getRolerights() {
		return this.rolerights;
	}

	public void setRolerights(byte[] rolerights) {
		this.rolerights = rolerights;
	}

	public Date getUpdatecreatetime() {
		return this.updatecreatetime;
	}

	public void setUpdatecreatetime(Date updatecreatetime) {
		this.updatecreatetime = updatecreatetime;
	}

	public String getUpdateuserid() {
		return this.updateuserid;
	}

	public void setUpdateuserid(String updateuserid) {
		this.updateuserid = updateuserid;
	}

}
