package ctvit.hibernate.model;
// Generated 2016-10-13 15:36:54 by Hibernate Tools 4.0.0.Final

/**
 * RecordChannel generated by hbm2java
 */
public class RecordChannel implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String channelid;
	private String organizationid;
	private String channelname;
	private String channeldesc;
	private RecordOrganization organization;
	public RecordOrganization getOrganization() {
		return organization;
	}

	public void setOrganization(RecordOrganization organization) {
		this.organization = organization;
	}

	public RecordChannel() {
	}

	public RecordChannel(String channelid) {
		this.channelid = channelid;
	}

	public RecordChannel(String channelid, String organizationid, String channelname, String channeldesc) {
		this.channelid = channelid;
		this.organizationid = organizationid;
		this.channelname = channelname;
		this.channeldesc = channeldesc;
	}

	public String getChannelid() {
		return this.channelid;
	}

	public void setChannelid(String channelid) {
		this.channelid = channelid;
	}

	public String getOrganizationid() {
		return this.organizationid;
	}

	public void setOrganizationid(String organizationid) {
		this.organizationid = organizationid;
	}

	public String getChannelname() {
		return this.channelname;
	}

	public void setChannelname(String channelname) {
		this.channelname = channelname;
	}

	public String getChanneldesc() {
		return this.channeldesc;
	}

	public void setChanneldesc(String channeldesc) {
		this.channeldesc = channeldesc;
	}

}
