package ctvit.hibernate.model;
// Generated 2016-10-13 15:36:54 by Hibernate Tools 4.0.0.Final

/**
 * Test generated by hbm2java
 */
public class Test implements java.io.Serializable {

	private Integer id;

	public Test() {
	}

	public Test(Integer id) {
		this.id = id;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

}
